import { QuestionnaireTemplate } from '../types';

// Predefined questionnaire templates
export const questionnaireTemplates: QuestionnaireTemplate[] = [
  {
    id: 'code-generation',
    name: 'Code Generation',
    description: 'Generate prompts for code generation, debugging, or refactoring tasks',
    icon: 'code',
    questions: [
      {
        id: 'programming-language',
        type: 'text',
        label: 'Programming Language',
        placeholder: 'e.g., Python, JavaScript, Java',
        required: true,
      },
      {
        id: 'framework',
        type: 'text',
        label: 'Framework/Library',
        placeholder: 'e.g., React, Django, Spring',
        required: false,
      },
      {
        id: 'task-description',
        type: 'textarea',
        label: 'Task Description',
        placeholder: 'Describe what you want the code to do',
        required: true,
      },
      {
        id: 'requirements',
        type: 'textarea',
        label: 'Requirements',
        placeholder: 'List any specific requirements or constraints',
        required: false,
      },
      {
        id: 'input-output',
        type: 'textarea',
        label: 'Expected Input/Output',
        placeholder: 'Describe the expected inputs and outputs',
        required: false,
      },
      {
        id: 'code-style',
        type: 'textarea',
        label: 'Code Style Preferences',
        placeholder: 'Any specific coding style or patterns you prefer',
        required: false,
      },
      {
        id: 'include-tests',
        type: 'checkbox',
        label: 'Include unit tests',
        defaultValue: true,
      },
      {
        id: 'include-examples',
        type: 'checkbox',
        label: 'Include usage examples',
        defaultValue: true,
      },
      {
        id: 'additional-context',
        type: 'textarea',
        label: 'Additional Context',
        placeholder: 'Any other information that might be helpful',
        required: false,
      },
    ],
  },
  {
    id: 'content-creation',
    name: 'Content Creation',
    description: 'Generate prompts for blog posts, articles, social media content, etc.',
    icon: 'file-text',
    questions: [
      {
        id: 'content-type',
        type: 'select',
        label: 'Content Type',
        options: [
          { value: 'blog-post', label: 'Blog Post' },
          { value: 'article', label: 'Article' },
          { value: 'social-media', label: 'Social Media Post' },
          { value: 'email', label: 'Email' },
          { value: 'product-description', label: 'Product Description' },
          { value: 'other', label: 'Other' },
        ],
        required: true,
      },
      {
        id: 'target-audience',
        type: 'text',
        label: 'Target Audience',
        placeholder: 'Who is this content for?',
        required: true,
      },
      {
        id: 'tone',
        type: 'select',
        label: 'Tone',
        options: [
          { value: 'formal', label: 'Formal' },
          { value: 'conversational', label: 'Conversational' },
          { value: 'humorous', label: 'Humorous' },
          { value: 'technical', label: 'Technical' },
          { value: 'persuasive', label: 'Persuasive' },
          { value: 'inspirational', label: 'Inspirational' },
        ],
        required: true,
      },
      {
        id: 'main-topic',
        type: 'textarea',
        label: 'Main Topic',
        placeholder: 'What is the main topic or subject?',
        required: true,
      },
      {
        id: 'key-points',
        type: 'textarea',
        label: 'Key Points',
        placeholder: 'List the key points you want to include',
        required: false,
      },
      {
        id: 'content-length',
        type: 'select',
        label: 'Content Length',
        options: [
          { value: 'short', label: 'Short (< 300 words)' },
          { value: 'medium', label: 'Medium (300-800 words)' },
          { value: 'long', label: 'Long (800-1500 words)' },
          { value: 'very-long', label: 'Very Long (1500+ words)' },
        ],
        required: true,
      },
      {
        id: 'seo-keywords',
        type: 'textarea',
        label: 'SEO Keywords',
        placeholder: 'List any SEO keywords to include',
        required: false,
      },
      {
        id: 'additional-instructions',
        type: 'textarea',
        label: 'Additional Instructions',
        placeholder: 'Any other specific instructions',
        required: false,
      },
    ],
  },
  {
    id: 'image-generation',
    name: 'Image Generation',
    description: 'Generate prompts for AI image generation tools like DALL-E, Midjourney, or Stable Diffusion',
    icon: 'image',
    questions: [
      {
        id: 'image-subject',
        type: 'text',
        label: 'Subject',
        placeholder: 'What is the main subject of the image?',
        required: true,
      },
      {
        id: 'image-style',
        type: 'select',
        label: 'Style',
        options: [
          { value: 'photorealistic', label: 'Photorealistic' },
          { value: 'digital-art', label: 'Digital Art' },
          { value: 'oil-painting', label: 'Oil Painting' },
          { value: 'watercolor', label: 'Watercolor' },
          { value: 'sketch', label: 'Sketch' },
          { value: 'pixel-art', label: 'Pixel Art' },
          { value: '3d-render', label: '3D Render' },
          { value: 'anime', label: 'Anime' },
          { value: 'cyberpunk', label: 'Cyberpunk' },
          { value: 'other', label: 'Other' },
        ],
        required: true,
      },
      {
        id: 'image-mood',
        type: 'select',
        label: 'Mood',
        options: [
          { value: 'happy', label: 'Happy' },
          { value: 'sad', label: 'Sad' },
          { value: 'mysterious', label: 'Mysterious' },
          { value: 'dramatic', label: 'Dramatic' },
          { value: 'peaceful', label: 'Peaceful' },
          { value: 'energetic', label: 'Energetic' },
          { value: 'nostalgic', label: 'Nostalgic' },
          { value: 'futuristic', label: 'Futuristic' },
        ],
        required: false,
      },
      {
        id: 'color-palette',
        type: 'text',
        label: 'Color Palette',
        placeholder: 'e.g., vibrant, pastel, monochrome, dark',
        required: false,
      },
      {
        id: 'detailed-description',
        type: 'textarea',
        label: 'Detailed Description',
        placeholder: 'Provide a detailed description of what you want in the image',
        required: true,
      },
      {
        id: 'composition',
        type: 'textarea',
        label: 'Composition',
        placeholder: 'Describe the composition, framing, or layout',
        required: false,
      },
      {
        id: 'lighting',
        type: 'text',
        label: 'Lighting',
        placeholder: 'e.g., soft natural light, dramatic shadows, neon',
        required: false,
      },
      {
        id: 'avoid-elements',
        type: 'textarea',
        label: 'Elements to Avoid',
        placeholder: 'List any elements you want to avoid in the image',
        required: false,
      },
      {
        id: 'reference-images',
        type: 'textarea',
        label: 'Reference Images',
        placeholder: 'Describe or link to any reference images',
        required: false,
      },
    ],
  },
  {
    id: 'text-to-video',
    name: 'Text-to-Video',
    description: 'Generate prompts for AI video generation tools',
    icon: 'video',
    questions: [
      {
        id: 'video-concept',
        type: 'textarea',
        label: 'Video Concept',
        placeholder: 'Describe the overall concept of the video',
        required: true,
      },
      {
        id: 'video-style',
        type: 'select',
        label: 'Style',
        options: [
          { value: 'realistic', label: 'Realistic' },
          { value: 'animated', label: 'Animated' },
          { value: '3d-animation', label: '3D Animation' },
          { value: 'stop-motion', label: 'Stop Motion' },
          { value: 'motion-graphics', label: 'Motion Graphics' },
          { value: 'mixed-media', label: 'Mixed Media' },
        ],
        required: true,
      },
      {
        id: 'video-duration',
        type: 'select',
        label: 'Duration',
        options: [
          { value: 'very-short', label: 'Very Short (< 15 seconds)' },
          { value: 'short', label: 'Short (15-30 seconds)' },
          { value: 'medium', label: 'Medium (30-60 seconds)' },
          { value: 'long', label: 'Long (1-3 minutes)' },
          { value: 'very-long', label: 'Very Long (3+ minutes)' },
        ],
        required: true,
      },
      {
        id: 'scene-description',
        type: 'textarea',
        label: 'Scene Description',
        placeholder: 'Describe the scenes in sequence',
        required: true,
      },
      {
        id: 'characters',
        type: 'textarea',
        label: 'Characters',
        placeholder: 'Describe any characters that appear in the video',
        required: false,
      },
      {
        id: 'camera-movements',
        type: 'textarea',
        label: 'Camera Movements',
        placeholder: 'Describe any specific camera movements or angles',
        required: false,
      },
      {
        id: 'audio-description',
        type: 'textarea',
        label: 'Audio/Music',
        placeholder: 'Describe the audio or music you want',
        required: false,
      },
      {
        id: 'transitions',
        type: 'textarea',
        label: 'Transitions',
        placeholder: 'Describe any transitions between scenes',
        required: false,
      },
      {
        id: 'special-effects',
        type: 'textarea',
        label: 'Special Effects',
        placeholder: 'Describe any special effects you want',
        required: false,
      },
    ],
  },
];

export default questionnaireTemplates;
